local addonInfo, privateVars = ...

---------- init namespace ---------

if not EnKai then EnKai = {} end
if not EnKai.location then EnKai.location = {} end

---------- init local variables ---------

local _scenes = { ["Silver Landing"]={DE="Silberne Landung", loc={}},
                  ["Tempest Station"]={DE="Sturmposten", loc={}},
                  ["Flamespawn Crater"]={DE="Flammenbrutkrater", loc={}},
                  ["Camp Cyclone"]={DE="Zyklonlager", loc={}},
                  ["Catari Command Center"]={DE="Kommandozentrale Catari", loc={}},
                  ["Byriel's Division"]={DE="Byriels Teilung", loc={}},
                  ["Gilded Strand"]={DE="Güldenes Gestade", loc={}},
                  ["Thedeor's Circle"]={DE="Thedeors Zirkel", loc={}},
                  ["Snarebrush Grot"]={DE="Schlingenstrauchgrotte", loc={}},
                  ["Rocklift"]={DE="Felslift", loc={}},
                  ["Venific Locus"]={DE="Venefic-Stätte", loc={}},
                  ["Wellspring Flats"]={DE="Quellenebenen", loc={}},
                  ["Core Chamber"]={DE="Kernkammer", loc={}},
                  ["Builder's Causeway"]={DE="Baumeister-Damm", loc={}},
                  ["Darkfire Grove"]={DE="Dunkelfeuerhain", loc={}},
                  ["Hive Az'Zgez"]={DE="Az'Zgez-Nest", loc={}},
                  ["Lastlight"]={DE="Endlicht", loc={}},
                  ["Ashen Fault"]={DE="Aschebruch", loc={}},
                  ["Windfury Post"]={DE="Windzorn-Außenposten", loc={}},
                  ["Scoured Ledge"]={DE="Wetzkante", loc={}},
                  ["Broken Marsh"]={DE="Bruchmorast", loc={}},
                  ["Sandwarden Pass"]={DE="Sandwachtpass", loc={}},
                  ["Grim Awakening"]={DE="Grimmiges Erwachen", loc={}},
                  ["Shok Forest"]={DE="Shok-Wald", loc={}},
                  ["Perspice"]={DE="Perspice", loc={}},
                  ["The Chancel of Labors"]={DE="Altar der Arbeit", loc={}},
                  ["Briarcliff"]={DE="Dornstrauchklippe", loc={}},
                  ["Ruins of Gakulos"]={DE="Ruinen von Gakulos", loc={}},
                  ["Veiled Bastion"]={DE="Verborgene Bastion", loc={}},
                  ["Auditorium Carnos"]={DE="Auditorium Carnos", loc={}},
                  ["Gramaton Station"]={DE="Grammaton-Station", loc={}},
                  ["Fremon Run"]={DE="Fremon-Lauf", loc={}},
                  ["Spitescar Bank"]={DE="Grollnarben-Damm", loc={}},
                  ["Felfathom Cays"]={DE="Felfathom-Riffe", loc={}},
                  ["Runic Descent"]={DE="Runental", loc={}},
                  ["Mephitis Bog"]={DE="Mephitis-Sumpf", loc={}},
                  ["Seastone Bluff"]={DE="Meersteinklippe", loc={}},
                  ["Stone Nexus"]={DE="Steinnexus", loc={}},
                  ["Kirna's Arbor"]={DE="Kirnas Laube", loc={}},
                  ["Caer Kholum"]={DE="Caer Kholum", loc={}},
                  ["Overwatch Keep"]={DE="Wachfeste", loc={}},
                  ["Crown Hill"]={DE="Kronhügel", loc={}},
                  ["The Dread Fortune"]={DE="Die Fortuna Fatalis", loc={}},
                  ["Reservoir"]={DE="Reservoir", loc={}},
                  ["Hiberna Rainforest"]={DE="Hiberna-Regenwald", loc={}},
                  ["Sunblind Ascent"]={DE="Sonnenblindhang", loc={}},
                  ["Sanctum Watch"]={DE="Sanctumwacht", loc={}},
                  ["Overwatch"]={DE="Wache", loc={}},
                  ["Solstice Tower"]={DE="Solstice-Turm", loc={}},
                  ["Kestrel's Cry Ravine"]={DE="Falkenruf-Klamm", loc={}},
                  ["Treants' Grove"]={DE="Arborierhain", loc={}},
                  ["Far Mine Loop"]={DE="Minenbogen", loc={}},
                  ["Dustwind Hills"]={DE="Die Staubwindhügel", loc={}},
                  ["Wreck of the Galena"]={DE="Wrack der Galena", loc={}},
                  ["Soros Estate"]={DE="Soros-Anwesen", loc={}},
                  ["The Ossuary"]={DE="Das Beinhaus", loc={}},
                  ["Faen's Retreat"]={DE="Faens Zuflucht", loc={}},
                  ["Talos Landing"]={DE="Talos-Landung", loc={}},
                  ["Sandstorm Refuge"]={DE="Sandsturmzuflucht", loc={}},
                  ["Todrin Estate"]={DE="Todrin-Anwesen", loc={}},
                  ["Deadman Gorge"]={DE="Totenschlucht", loc={}},
                  ["Dormant Core"]={DE="Ruhender Kern", loc={}},
                  ["Thunderwork Ridge"]={DE="Donnerwerkjoch", loc={}},
                  ["Broodwatch Post"]={DE="Brutwacht-Posten", loc={}},
                  ["Royal Gardens"]={DE="Königliche Gärten", loc={}},
                  ["Temple of Thontic"]={DE="Tempel des Thontic", loc={}},
                  ["Moonrise Hollow"]={DE="Mondscheinhöhle", loc={}},
                  ["Blood Iron Pools"]={DE="Bluteisenbecken", loc={}},
                  ["Last Hope"]={DE="Letzte Hoffnung", loc={}},
                  ["Scoria Pit"]={DE="Schlackengrube", loc={}},
                  ["Abundant Wilds"]={DE="Üppige Wildnis", loc={}},
                  ["Ardenburgh Gate"]={DE="Ardenburgh-Tor", loc={}},
                  ["Twisted Hollow"]={DE="Wirre Senke", loc={}},
                  ["Broken Road"]={DE="Bruchstraße", loc={}},
                  ["Villa Orphela"]={DE="Villa Orphela", loc={}},
                  ["Halcyon Gates"]={DE="Tore der Glückseligkeit", loc={}},
                  ["Argent Glade"]={DE="Silberfeld", loc={}},
                  ["Splintered Shallows"]={DE="Splitterfurt", loc={}},
                  ["Akelthix"]={DE="Akelthix", loc={}},
                  ["Grey Gardens"]={DE="Graugärten", loc={}},
                  ["The Endless Citadel"]={DE="Die Ewige Zitadelle", loc={}},
                  ["Lair of the Abandoned"]={DE="Versteck der Verlassenen", loc={}},
                  ["Savage Wilds"]={DE="Grausame Wildnis", loc={}},
                  ["Centaurs' Stand"]={DE="Zentaurenholz", loc={}},
                  ["Spitescar Wash"]={DE="Grollnarbenbach", loc={}},
                  ["Vengeful Sky"]={DE="Schwebende Rachsucht", loc={}},
                  ["Quarrystone Basin"]={DE="Bruchsteinbecken", loc={}},
                  ["Mongrel Foothills"]={DE="Bastard-Ausläufer", loc={}},
                  ["Cesspool of Misshapen Children"]={DE="Sumpf der missgebildeten Kinder", loc={}},
                  ["Ravenna"]={DE="Ravenna", loc={}},
                  ["Divine Landing"]={DE="Göttlicher Anlegeplatz", loc={}},
                  ["Toppled Coast"]={DE="Sturzküste", loc={}},
                  ["Greanta River Canyon"]={DE="Canyon des Greanta-Flusses", loc={}},
                  ["Redoubt"]={DE="Steinerne Ruine", loc={}},
                  ["Savage Hill"]={DE="Wildhügel", loc={}},
                  ["Atia"]={DE="Atia", loc={}},
                  ["LIGHTING for Thunder Hills"]={DE="BELEUCHTUNG für Donnerhügel", loc={}},
                  ["Harbor"]={DE="Port", loc={}},
                  ["Blood Grove"]={DE="Bluthain", loc={}},
                  ["Lowlands Gulley"]={DE="Tieflandfurche", loc={}},
                  ["Icewatch Ridge"]={DE="Eiswachtgrat", loc={}},
                  ["Pit of Mastery"]={DE="Grube der Beherrschung", loc={}},
                  ["Marsh House"]={DE="Sumpfhaus", loc={}},
                  ["Gates of Carcera"]={DE="Tore von Carcera", loc={}},
                  ["Shadefallen Keep"]={DE="Festung Schattensturz", loc={}},
                  ["Loggerman's Lift"]={DE="Holzfällerheber", loc={}},
                  ["Iron Tomb Passage"]={DE="Eisengrab-Passage", loc={}},
                  ["Grove Lift"]={DE="Hainheber", loc={}},
                  ["Scarwood Ridge"]={DE="Wundwaldgrat", loc={}},
                  ["Circle of Flame"]={DE="Kreis der Flamme", loc={}},
                  ["Mirror Of Ages"]={DE="Spiegel der Zeiten", loc={}},
                  ["Cydrel's Rest"]={DE="Cydrels Rast", loc={}},
                  ["Gnawbone Valley"]={DE="Nagebeintal", loc={}},
                  ["Scarred Mire"]={DE="Narbenmoor", loc={}},
                  ["Warden's Point"]={DE="Wachtkap", loc={}},
                  ["Thontic's Row"]={DE="Thontics Zeile", loc={}},
                  ["Halls of Abduction"]={DE="Hallen der Entführung", loc={}},
                  ["Vizeya"]={DE="Vizeya", loc={}},
                  ["Abyssal Precipice"]={DE="Abgründige Kluft", loc={}},
                  ["Tearfall Run"]={DE="Zährenbach", loc={}},
                  ["Bloodmurk Grove"]={DE="Blutnebelhain", loc={}},
                  ["Breach Chamber"]={DE="Königsbresche", loc={}},
                  ["Charred Chasm"]={DE="Kohlenschwarze Kluft", loc={}},
                  ["Throne Room"]={DE="Der Thronsaal", loc={}},
                  ["Smith's Haven"]={DE="Schmittshafen", loc={}},
                  ["Sanctum of the Vigil"]={DE="Allerheiligstes der Vigilie", loc={}},
                  ["Lambent Gap"]={DE="Funkelgrotte", loc={}},
                  ["Sanco Outpost"]={DE="Sanco-Außenposten", loc={}},
                  ["Cambium Loci"]={DE="Cambium-Stätten", loc={}},
                  ["Cirkbo Plains"]={DE="Cirkbo-Ebenen", loc={}},
                  ["Witch's Thicket"]={DE="Hexendickicht", loc={}},
                  ["Gnarlwood Post"]={DE="Knorzwaldposten", loc={}},
                  ["Frozen Valley"]={DE="Frosttal", loc={}},
                  ["The Manufactory"]={DE="Die Manufaktur", loc={}},
                  ["The Sinkhole"]={DE="Das Schluckloch", loc={}},
                  ["Ruston"]={DE="Ruston", loc={}},
                  ["Bahralt Street"]={DE="Bahralt-Straße", loc={}},
                  ["Menagerie"]={DE="Menagerie", loc={}},
                  ["Khaliti Refuge"]={DE="Khaliti-Zuflucht", loc={}},
                  ["Cliffside Vale"]={DE="Klippental", loc={}},
                  ["Lantern Plateau"]={DE="Laternenplateau", loc={}},
                  ["The Hammerhead"]={DE="Der Hammerkopf", loc={}},
                  ["Searing Brink"]={DE="Glutrand", loc={}},
                  ["Titan's Well"]={DE="Titanenbrunnen", loc={}},
                  ["Hillcrest"]={DE="Hügelkrone", loc={}},
                  ["Temblor Hills"]={DE="Temblorhügel", loc={}},
                  ["Optheron"]={DE="Optheron", loc={}},
                  ["Riverbank Cutoff"]={DE="Flussufer-Abkürzung", loc={}},
                  ["Old Mule Run"]={DE="Maultierpiste", loc={}},
                  ["Crook Ridge"]={DE="Gaunergrat", loc={}},
                  ["Dreadbone Shelf"]={DE="Grausknochen-Grat", loc={}},
                  ["Stormhold"]={DE="Sturmfestung", loc={}},
                  ["Edgestone Ridge"]={DE="Kantstein-Grat", loc={}},
                  ["Cassana Estate"]={DE="Cassana-Anwesen", loc={}},
                  ["Shapers Citadel"]={DE="Zitadelle der Gestalter", loc={}},
                  ["The Oasis"]={DE="Die Oase", loc={}},
                  ["The Breach"]={DE="Die Bresche", loc={}},
                  ["Sundered Path"]={DE="Trennpfad", loc={}},
                  ["Bronze Tomb Passage"]={DE="Bronzegrab-Passage", loc={}},
                  ["Hive Kaaz'Gfuu"]={DE="Kaaz'Gfuu-Nest", loc={}},
                  ["Iala's Point"]={DE="Ialas Punkt", loc={}},
                  ["Fractured Plain"]={DE="Bruchebene", loc={}},
                  ["Necropolis"]={DE="Nekropolis", loc={}},
                  ["Hullbreach Shoals"]={DE="Schiffbruchsandbank", loc={}},
                  ["The Training Yard"]={DE="Übungshof", loc={}},
                  ["Spice Road"]={DE="Gewürzroute", loc={}},
                  ["Sanguine Shores"]={DE="Blutige Küsten", loc={}},
                  ["Arcanum Conservatory"]={DE="Konservatorium von Arcanum", loc={}},
                  ["Epoch Plaza"]={DE="Epochenplatz", loc={}},
                  ["Nykantor Ruins"]={DE="Nykantor-Ruinen", loc={}},
                  ["Arkella Estate"]={DE="Arkella-Anwesen", loc={}},
                  ["Tomb of the Consort"]={DE="Grab des Gefährten", loc={}},
                  ["Death's Doorstep"]={DE="Schwelle des Todes", loc={}},
                  ["Kelari Refuge"]={DE="Kelari-Zuflucht", loc={}},
                  ["Dawnkeeper Vale"]={DE="Dämmerungshüter-Tal", loc={}},
                  ["The Flatyard"]={DE="Der Flachhof", loc={}},
                  ["Mistfall Cove"]={DE="Nebelbucht", loc={}},
                  ["Acrid Basin"]={DE="Bitterbecken", loc={}},
                  ["Daemon Loci"]={DE="Dämonenstätten", loc={}},
                  ["Tuldio Retreat"]={DE="Tuldio-Zuflucht", loc={}},
                  ["Widow's Perch"]={DE="Witwenthron", loc={}},
                  ["The Fall of Lantern Hook"]={DE="Der Untergang von Laternenhaken", loc={}},
                  ["Cutpurse Alley"]={DE="Langfingergässchen", loc={}},
                  ["Eye of Regulos"]={DE="Auge des Regulos", loc={}},
                  ["Northern Cross"]={DE="Nördliche Kreuzung", loc={}},
                  ["Southwall Bunker"]={DE="Südwallbunker", loc={}},
                  ["Dagger's Edge"]={DE="Dolchgrat", loc={}},
                  ["Harlan's Lament"]={DE="Harlans Klage", loc={}},
                  ["Death's Approach"]={DE="Todestor", loc={}},
                  ["Mired Convoy"]={DE="Sumpf-Konvoi", loc={}},
                  ["Fort Mazamar"]={DE="Bastion Mazamar", loc={}},
                  ["Knight's Stand"]={DE="Ritterposten", loc={}},
                  ["Coterie Camp"]={DE="Lager Klüngel", loc={}},
                  ["Demon Steps"]={DE="Dämonentreppe", loc={}},
                  ["Dayblind Hollows"]={DE="Tagesblindhöhlen", loc={}},
                  ["Core of Carcera"]={DE="Kern von Carcera", loc={}},
                  ["Orphiel's Spire"]={DE="Orphiels Turm", loc={}},
                  ["Denegar's Stand"]={DE="Denegars Stand", loc={}},
                  ["The Golden Hoard"]={DE="Der Goldene Hort", loc={}},
                  ["Black Strand"]={DE="Schwarze Gestade", loc={}},
                  ["Twilit Stand"]={DE="Zwielichtstand", loc={}},
                  ["The Eternal Assault"]={DE="Der Endlose Ansturm", loc={}},
                  ["Hunters' Camp"]={DE="Jägerlager", loc={}},
                  ["Blighted Pit"]={DE="Elendsgrube", loc={}},
                  ["Temple of the Abandoned"]={DE="Tempel der Verlassenen", loc={}},
                  ["Trial of the Sentinel"]={DE="Prüfung der Schildwache", loc={}},
                  ["Deepstrike Excavation"]={DE="Tiefschlag-Ausgrabung", loc={}},
                  ["Stonecrest"]={DE="Steinkrone", loc={}},
                  ["Ruinous Passage"]={DE="Ruinen-Passage", loc={}},
                  ["Storehouse Cassana"]={DE="Cassana-Lagerhaus", loc={}},
                  ["Darkrun Wreckage"]={DE="Düsterlauf-Wrack", loc={}},
                  ["Ruins of Tammark"]={DE="Ruinen von Tammark", loc={}},
                  ["Path of Princes"]={DE="Pfad der Prinzen", loc={}},
                  ["Santi Village"]={DE="Santi-Dorf", loc={}},
                  ["Hammerknell Fortress"]={DE="Festung Hammerhall", loc={}},
                  ["Exile's Den"]={DE="Versteck des Verbannten", loc={}},
                  ["Iron Tomb"]={DE="Eisengrab", loc={}},
                  ["Timberveil"]={DE="Holzflor", loc={}},
                  ["King's Retreat"]={DE="Königliches Refugium", loc={}},
                  ["Scaldwater Fields"]={DE="Brühwasserfelder", loc={}},
                  ["Castrum Hiberna"]={DE="Castrum Hiberna", loc={}},
                  ["Daazez Wastes"]={DE="Daazez-Ödnis", loc={}},
                  ["Karthan Hills"]={DE="Karthahügel", loc={}},
                  ["Trapper's Rest"]={DE="Trappers Rast", loc={}},
                  ["Howling Hills"]={DE="Heulende Hügel", loc={}},
                  ["Stonefield Prairie"]={DE="Steinfeldprärie", loc={}},
                  ["Arakhosian Hinterlands"]={DE="Hinterland von Arakhosia", loc={}},
                  ["World's End"]={DE="Das Ende der Welt", loc={}},
                  ["Granite Falls"]={DE="Granitsturz", loc={}},
                  ["Keenblade Barricade"]={DE="Scharfklingenbarrikade", loc={}},
                  ["Rugan's Lea"]={DE="Rugans Aue", loc={}},
                  ["Stonekey Court"]={DE="Steinschlüsselhof", loc={}},
                  ["Majeric Tower"]={DE="Majeric-Turm", loc={}},
                  ["Korolis Valley"]={DE="Korolis-Tal", loc={}},
                  ["Timar Foothills"]={DE="Timar-Vorland", loc={}},
                  ["Charmer's Caldera"]={DE="Zaubererkessel", loc={}},
                  ["Trollblight Caverns"]={DE="Trollpesthöhlen", loc={}},
                  ["Public Market"]={DE="Öffentlicher Markt", loc={}},
                  ["Trawling Post"]={DE="Fischerhafen", loc={}},
                  ["Bilgewater Grotto"]={DE="Bilgenwassergrotte", loc={}},
                  ["Auroborus Woods"]={DE="Auroborus-Wald", loc={}},
                  ["Camp Vigil"]={DE="Lager der Vigilie", loc={}},
                  ["Suncrest Rise"]={DE="Sonngipfel", loc={}},
                  ["Molinar Crossing"]={DE="Molinar-Kreuzweg", loc={}},
                  ["Vaud Tower"]={DE="Vaud-Turm", loc={}},
                  ["Zerzala"]={DE="Zerzala", loc={}},
                  ["The Iron Fortress"]={DE="Die Eiserne Festung", loc={}},
                  ["Great Library"]={DE="Große Bibliothek", loc={}},
                  ["The Armory"]={DE="Das Arsenal", loc={}},
                  ["Towering Steppes"]={DE="Gewaltige Steppen", loc={}},
                  ["Creep of Oblivion"]={DE="Wirren der Vergessenheit", loc={}},
                  ["Howling Caves"]={DE="Heulende Höhlen", loc={}},
                  ["Shoreward Island"]={DE="Küstensicht-Insel", loc={}},
                  ["Thontic's Fountain"]={DE="Thontics Brunnen", loc={}},
                  ["Jeweled Heights"]={DE="Juwelenhöhen", loc={}},
                  ["Sandaxle Pit"]={DE="Sandachsengrube", loc={}},
                  ["Mount Hejir"]={DE="Hejir", loc={}},
                  ["Valley of Iron"]={DE="Eisental", loc={}},
                  ["Icewatch Outpost"]={DE="Eiswacht-Außenposten", loc={}},
                  ["Ferric Harbor"]={DE="Rosthafen", loc={}},
                  ["Scarwood Lift Base"]={DE="Wundwald-Lift, loc={}}, Basis", loc={}},
                  ["The Boneforge"]={DE="Die Knochenschmiede", loc={}},
                  ["Carrion Heights"]={DE="Aashöhen", loc={}},
                  ["Wolfsbane"]={DE="Wolfsbann", loc={}},
                  ["Arlan's Challenge"]={DE="Arlans Herausforderung", loc={}},
                  ["Ironroot Draw"]={DE="Eisenwurzelschacht", loc={}},
                  ["Dream Furnace"]={DE="Traum-Brutofen", loc={}},
                  ["The Academy"]={DE="Die Akademie", loc={}},
                  ["Cloudbourne Caverns"]={DE="Wolkenhöhlen", loc={}},
                  ["Solemn Outlook"]={DE="Düsterer Ausblick", loc={}},
                  ["The Caul"]={DE="Die Glückshaube", loc={}},
                  ["Glimmering Light"]={DE="Glimmlicht", loc={}},
                  ["Valley of Bones"]={DE="Tal der Knochen", loc={}},
                  ["Miran Gate"]={DE="Miran-Tor", loc={}},
                  ["Edgewood"]={DE="Grenzwald", loc={}},
                  ["Deepwood Cottage"]={DE="Tiefwaldhütte", loc={}},
                  ["King's Breach"]={DE="Königsbresche", loc={}},
                  ["Whitefall Passage"]={DE="Weißfall-Passage", loc={}},
                  ["Gildstone Sanctum"]={DE="Güldenstein-Heiligtum", loc={}},
                  ["Stonemason's Watch"]={DE="Steinmetzwache", loc={}},
                  ["Ember Watch"]={DE="Glutwacht", loc={}},
                  ["Chasm of Eternal Fire"]={DE="Kluft des ewigen Feuers", loc={}},
                  ["Lord's Hall"]={DE="Herrscherhalle", loc={}},
                  ["Auld Warden"]={DE="Alte Wache", loc={}},
                  ["Defiant's Approach"]={DE="Skeptikerschneise", loc={}},
                  ["Jurota Lakes"]={DE="Jurota-Seen", loc={}},
                  ["Hillsborough"]={DE="Hügelberg", loc={}},
                  ["Breaker Point"]={DE="Bruchpunkt", loc={}},
                  ["Steampike Pit"]={DE="Dampfstachelgrube", loc={}},
                  ["Hallowed Hill"]={DE="Geheiligter Hügel", loc={}},
                  ["College of Planar Studies"]={DE="Akademie für Ebenenstudien", loc={}},
                  ["Crusader's Advance"]={DE="Ritterhöhe", loc={}},
                  ["Great Hall"]={DE="Große Halle", loc={}},
                  ["Agrippa Rainforest"]={DE="Agrippa-Regenwald", loc={}},
                  ["Rock Ridge"]={DE="Felsgrat", loc={}},
                  ["Granite Watch"]={DE="Granitwache", loc={}},
                  ["Cloudbourne Tarn"]={DE="Wolkentümpel", loc={}},
                  ["Molten Verge"]={DE="Schmelzschneide", loc={}},
                  ["Lakeside Outpost"]={DE="Seeblick-Außenposten", loc={}},
                  ["The Infinity Gate"]={DE="Tor der Unendlichkeit", loc={}},
                  ["Halls of Decay"]={DE="Hallen des Verfalls", loc={}},
                  ["Regent's Fall"]={DE="Regentensturz", loc={}},
                  ["Fort Zarnost"]={DE="Bastion Zarnost", loc={}},
                  ["Thalin Tor"]={DE="Thalin Tor", loc={}},
                  ["Greenscale's Crater"]={DE="Grünschuppes Krater", loc={}},
                  ["Expedition Camp"]={DE="Expeditionslager", loc={}},
                  ["Moonshade Pools"]={DE="Mondschatten-Weiher", loc={}},
                  ["Lost March"]={DE="Verlorene Mark", loc={}},
                  ["Strozza Estate"]={DE="Strozza-Anwesen", loc={}},
                  ["Lake of Solace"]={DE="See des Trostes", loc={}},
                  ["Threshold of Mortality"]={DE="Schwelle der Sterblichkeit", loc={}},
                  ["Dead Pass"]={DE="Totenpass", loc={}},
                  ["Malluma Basin"]={DE="Mallumabecken", loc={}},
                  ["Achyati Village"]={DE="Achyati-Dorf", loc={}},
                  ["Glacio Mountains"]={DE="Glaziogebirge", loc={}},
                  ["The Wild"]={DE="Die Wildnis", loc={}},
                  ["Mariel-Taun's Village"]={DE="Mariel-Tauns Dorf", loc={}},
                  ["Dawnbreak Point"]={DE="Kap Morgenrot", loc={}},
                  ["Reclaimer's Hold"]={DE="Kahlschlägerlager", loc={}},
                  ["Enytharis"]={DE="Enytharis", loc={}},
                  ["Hall of Avarice"]={DE="Halle der Habsucht", loc={}},
                  ["Endless Watch"]={DE="Ewige Wacht", loc={}},
                  ["Greybriar Hollow"]={DE="Graustrauchkuhle", loc={}},
                  ["Temple of the Moon"]={DE="Mondtempel", loc={}},
                  ["King's Corridor"]={DE="Königskorridor", loc={}},
                  ["Kingsgate"]={DE="Königstor", loc={}},
                  ["Autumn Terrace"]={DE="Herbstterrasse", loc={}},
                  ["Obsidian Shore"]={DE="Obsidian-Küste", loc={}},
                  ["Riverfell"]={DE="Flussfels", loc={}},
                  ["Quicksilver College"]={DE="Quecksilber-Akademie", loc={}},
                  ["Progenitor's Laboratory"]={DE="Labor des Erzeugers", loc={}},
                  ["Forlorn Fen"]={DE="Tristmoor", loc={}},
                  ["Blightweald"]={DE="Seuchenlande", loc={}},
                  ["Radiant Guard"]={DE="Strahlenwacht", loc={}},
                  ["Infinity Holding Facility"]={DE="Unendlichkeits-Aufbewahrungseinrichtung", loc={}},
                  ["Quarrystone Base Camp"]={DE="Bruchsteinbecken-Basislager", loc={}},
                  ["Crystal Depths"]={DE="Kristalltiefen", loc={}},
                  ["Haunted Terminal"]={DE="Verfluchtes Terminal", loc={}},
                  ["The Stranglewood"]={DE="Der Würgwald", loc={}},
                  ["Broken Toe"]={DE="Zehenbruch", loc={}},
                  ["Sundred Trenches"]={DE="Getrennte Gräben", loc={}},
                  ["Quarrystone Pass"]={DE="Bruchsteinpass", loc={}},
                  ["Sunrest Canyon"]={DE="Sonnrastschlucht", loc={}},
                  ["Riptalon Gulch"]={DE="Reißkrallenschlucht", loc={}},
                  ["The Biofoundry"]={DE="Die Lebensgießerei", loc={}},
                  ["Scarwood Lift Summit"]={DE="Wundwald-Lift, loc={}}, Bergstation", loc={}},
                  ["The Charred Stair"]={DE="Die verbrannte Stufe", loc={}},
                  ["Camp Fergos"]={DE="Fergos-Lager", loc={}},
                  ["Vigilant Rise"]={DE="Wachsame Höhen", loc={}},
                  ["Sunken Marsh"]={DE="Sinksumpf", loc={}},
                  ["Mount Carcera"]={DE="Carcera", loc={}},
                  ["Camp Cestus"]={DE="Cestuslager", loc={}},
                  ["Millrush Pond"]={DE="Mühlenteich", loc={}},
                  ["Camp Landfall"]={DE="Landungslager", loc={}},
                  ["Tower of Dawn"]={DE="Der Turm der Morgenröte", loc={}},
                  ["The Canals"]={DE="Die Kanäle", loc={}},
                  ["Granitewood Haunt"]={DE="Granitwaldgegend", loc={}},
                  ["Aurora Maelstrom"]={DE="Sturm der Morgenröte", loc={}},
                  ["Dunes of Akala"]={DE="Dünen von Akala", loc={}},
                  ["Old Meadow Farm"]={DE="Farm zur Alten Weide", loc={}},
                  ["Whitefall Lift"]={DE="Weißfall-Lift", loc={}},
                  ["Highglades Lookout"]={DE="Hochalm-Ausblick", loc={}},
                  ["Falsehood Slope"]={DE="Lügenböschung", loc={}},
                  ["Leestone Stand"]={DE="Leestein-Posten", loc={}},
                  ["Broken Vale"]={DE="Bruchtal", loc={}},
                  ["Belmont"]={DE="Belmont", loc={}},
                  ["Mathosian Mill"]={DE="Mathosianische Mühle", loc={}},
                  ["Wyrmbane Spire"]={DE="Wurmfluchspitze", loc={}},
                  ["Seersage Camp"]={DE="Seherweisen-Lager", loc={}},
                  ["Tempest Plains"]={DE="Sturmebenen", loc={}},
                  ["Regent's Cove"]={DE="Regentenbucht", loc={}},
                  ["Stone Grove"]={DE="Steinhain", loc={}},
                  ["Hailol"]={DE="Hailol", loc={}},
                  ["Fetid Plains"]={DE="Faulige Ebenen", loc={}},
                  ["The Last Valley"]={DE="Das Endtal", loc={}},
                  ["Western Commons"]={DE="West-Allmende", loc={}},
                  ["Valor Hold"]={DE="Tapferkeitsfeste", loc={}},
                  ["Endless Eclipse"]={DE="Ewige Sonnenfinsternis", loc={}},
                  ["Azcu'azg Oasis"]={DE="Azcu'azg-Oase", loc={}},
                  ["Lotham's Strike"]={DE="Lothams Schlag", loc={}},
                  ["Den of Kwell"]={DE="Höhle des Kwell", loc={}},
                  ["Hammerlord Post"]={DE="Hammerfürst-Posten", loc={}},
                  ["Rockstrewn Acres"]={DE="Geröllacker", loc={}},
                  ["Citizen's Library"]={DE="Öffentliche Bücherhalle", loc={}},
                  ["Silkweb Pass"]={DE="Seidennetzpass", loc={}},
                  ["Mordant Knolls"]={DE="Bisshügel", loc={}},
                  ["Sterling Hills"]={DE="Silberhöhen", loc={}},
                  ["Faemist Point"]={DE="Kap Feendunst", loc={}},
                  ["Ashen Descent"]={DE="Aschesenke", loc={}},
                  ["Kelthenas Basin"]={DE="Kelthenas-Becken", loc={}},
                  ["Phoenix Rise"]={DE="Phönixhöhe", loc={}},
                  ["Arjuros"]={DE="Arjuros", loc={}},
                  ["Orphiel's Observatory"]={DE="Orphiels Observatorium", loc={}},
                  ["Theater District"]={DE="Theaterbezirk", loc={}},
                  ["Standing Stones"]={DE="Stehende Steine", loc={}},
                  ["Fallback"]={DE="Fallbach", loc={}},
                  ["Whitefall"]={DE="Weißfall", loc={}},
                  ["Ardenburgh"]={DE="Ardenburgh", loc={}},
                  ["The Stormbreach"]={DE="Die Sturmbresche", loc={}},
                  ["Eliam Fields"]={DE="Eliamfelder", loc={}},
                  ["Bahralt's Ascent"]={DE="Bahralts Anhöhe", loc={}},
                  ["Spirit of Rhaza'de"]={DE="Geist von Rhaza'de", loc={}},
                  ["Stalwart Rise"]={DE="Getreuenhöhe", loc={}},
                  ["Quarry of the Architects"]={DE="Steinbruch der Architekten", loc={}},
                  ["Anima Loci"]={DE="Anima-Stätten", loc={}},
                  ["Kindra's Thicket"]={DE="Kindra-Dickicht", loc={}},
                  ["Caer Mathos"]={DE="Caer Mathos", loc={}},
                  ["Shatterbone Hold"]={DE="Knochenberster-Bastion", loc={}},
                  ["Hammerknell Steps"]={DE="Stufen von Hammerhall", loc={}},
                  ["Golden Summit"]={DE="Goldener Gipfel", loc={}},
                  ["Passage of the Seer"]={DE="Passage des Sehers", loc={}},
                  ["Gritsquall Haven"]={DE="Scheuerschwallhafen", loc={}},
                  ["Keenblade Mill"]={DE="Scharfklingenmühle", loc={}},
                  ["Fortune's End"]={DE="Glücksend", loc={}},
                  ["Temple of Marakris"]={DE="Tempel von Marakris", loc={}},
                  ["Splitmouth Ponds"]={DE="Spaltrachenweiher", loc={}},
                  ["West Deepwood Trail"]={DE="Westlicher Tiefwaldpfad", loc={}},
                  ["Brink of Angoro"]={DE="Angoro-Abgrund", loc={}},
                  ["Tulan Bay"]={DE="Tulan-Bucht", loc={}},
                  ["Heroes' Stand"]={DE="Heldentrutz", loc={}},
                  ["Behemoth Graveyard"]={DE="Friedhof der Ungetüme", loc={}},
                  ["Tidewell Inlet"]={DE="Gezeitenbrunnen-Zufluss", loc={}},
                  ["Firesand Desert"]={DE="Feuersandwüste", loc={}},
                  ["Untamed Copse"]={DE="Verwildertes Dickicht", loc={}},
                  ["Hedgerow Court"]={DE="Heckenhof", loc={}},
                  ["Ember Corridor"]={DE="Glutkorridor", loc={}},
                  ["Thontic Shallows"]={DE="Thontic-Furt", loc={}},
                  ["Three Springs"]={DE="Dreienquell", loc={}},
                  ["Rooh Jungle"]={DE="Rooh-Dschungel", loc={}},
                  ["Kelpmere"]={DE="Tangweiher", loc={}},
                  ["Darkening Deeps"]={DE="Finstere Tiefen", loc={}},
                  ["Boneforged Cathedral"]={DE="Knochengeschmiedete Kathedrale", loc={}},
                  ["Farsight Tower"]={DE="Fernblick-Turm", loc={}},
                  ["Crescent Ridge"]={DE="Halbmondkamm", loc={}},
                  ["Nomad's Furnace"]={DE="Nomadenofen", loc={}},
                  ["Boundary Ruins"]={DE="Grenzruinen", loc={}},
                  ["Tulan"]={DE="Tulan", loc={}},
                  ["Rubicon"]={DE="Rubikon", loc={}},
                  ["Camp Skyburst"]={DE="Himmelbruch-Lager", loc={}},
                  ["Camp Talon"]={DE="Krallenlager", loc={}},
                  ["Thedeor Fields"]={DE="Thedeor-Felder", loc={}},
                  ["Kheramos Village"]={DE="Kheramos", loc={}},
                  ["Frayworn Rock"]={DE="Schlachtenfels", loc={}},
                  ["Ursin Grove Bunker"]={DE="Bärenhain-Bunker", loc={}},
                  ["The Rill Pond"]={DE="Der Rillteich", loc={}},
                  ["The Harrow"]={DE="Die Egge", loc={}},
                  ["Stormbrood Lair"]={DE="Sturmbrutversteck", loc={}},
                  ["Tavril Plaza"]={DE="Tavril-Plaza", loc={}},
                  ["The Crawl"]={DE="Der Schlund", loc={}},
                  ["Fell Fields"]={DE="Höllenfelder", loc={}},
                  ["Fortune's Shore"]={DE="Glücksküste", loc={}},
                  ["Shivered Bluffs"]={DE="Schlotterklippe", loc={}},
                  ["Clods Hollow"]={DE="Klumpenkuhle", loc={}},
                  ["Deepstrike Mines"]={DE="Tiefschlagmine", loc={}},
                  ["Crimson Wash"]={DE="Purpurbach", loc={}},
                  ["Infested Range"]={DE="Verseuchtes Feld", loc={}},
                  ["Crystalline Grotto"]={DE="Kristallgrotte", loc={}},
                  ["Hive Zg'Kaa"]={DE="Zg'Kaa-Nest", loc={}},
                  ["The Sub-Chamber"]={DE="Die Subkammer", loc={}},
                  ["The Sagespire"]={DE="Der Turm der Weisen", loc={}},
                  ["Fen Gorge Bunker"]={DE="Moorschlucht-Bunker", loc={}},
                  ["Mage's Mark"]={DE="Magierzeichen", loc={}},
                  ["Lair of Aetleron"]={DE="Versteck von Aetleron", loc={}},
                  ["Kain's Command"]={DE="Kains Kommandoposten", loc={}},
                  ["The Northern Ruins"]={DE="Die Nordruinen", loc={}},
                  ["Wayward Thicket"]={DE="Spenststrüpp", loc={}},
                  ["Vestige"]={DE="Überbleibsel", loc={}},
                  ["Ark of the Ascended"]={DE="Arche der Auserwählten", loc={}},
                  ["Palisade"]={DE="Palisade", loc={}},
                  ["Burlingham"]={DE="Burlingham", loc={}},
                  ["Mordant Warren"]={DE="Bissgang", loc={}},
                  ["Aqueduct"]={DE="Aquädukt", loc={}},
                  ["Dolcega Valley"]={DE="Dolcega-Tal", loc={}},
                  ["Den of Lezul"]={DE="Höhle des Lezul", loc={}},
                  ["Grove of the Ancients"]={DE="Hain der Alten", loc={}},
                  ["Rockswept Heaps"]={DE="Felssturz-Halde", loc={}},
                  ["The Black Stables"]={DE="Die Schwarzen Ställe", loc={}},
                  ["Warden's Descent"]={DE="Wachtschlucht", loc={}},
                  ["Farhall"]={DE="Fernhall", loc={}},
                  ["Howling Plateau"]={DE="Heulendes Plateau", loc={}},
                  ["Seafarer's Folly"]={DE="Seemannstorheit", loc={}},
                  ["Pilgrim's Crossing"]={DE="Pilgerkreuzweg", loc={}},
                  ["Foul Cascade"]={DE="Ekelkaskade", loc={}},
                  ["Koke's Hold"]={DE="Kokes Festung", loc={}},
                  ["Aurentine Palace"]={DE="Aurentine-Palast", loc={}},
                  ["Fletcher's Beach"]={DE="Schäfterstrand", loc={}},
                  ["Etched Plains"]={DE="Stichprärie", loc={}},
                  ["Granitedust Gulch"]={DE="Granitstaubschlucht", loc={}},
                  ["Jagged Fringe"]={DE="Zackenrand", loc={}},
                  ["Frost Falls"]={DE="Frostfälle", loc={}},
                  ["Lantern Hook"]={DE="Laternenhaken", loc={}},
                  ["The Hollow"]={DE="Die Höhle", loc={}},
                  ["Plaza Aurentine"]={DE="Aurentine-Platz", loc={}},
                  ["Faering Woods"]={DE="Feenring-Forst", loc={}},
                  ["The Dragon's Tail"]={DE="Drachenschweif", loc={}},
                  ["Realm of the Fae"]={DE="Reich der Feen", loc={}},
                  ["Silver Coast"]={DE="Silberküste", loc={}},
                  ["Sunrest Bridge"]={DE="Sonnrastbrücke", loc={}},
                  ["Turnis River Bunker"]={DE="Turnis-Bunker", loc={}},
                  ["Fort Antapo"]={DE="Bastion Antapo", loc={}},
                  ["Forest of Flesh"]={DE="Fleischwald", loc={}},
                  ["Khaliti Row"]={DE="Khaliti-Zeile", loc={}},
                  ["Zareph's Return"]={DE="Zarephs Wiederkehr", loc={}},
                  ["Iron Fall"]={DE="Eisenfall", loc={}},
                  ["Cutthroat Cove"]={DE="Mörderbucht", loc={}},
                  ["Static Vale"]={DE="Statisches Tal", loc={}},
                  ["Brigand's Bluff"]={DE="Räuberklippe", loc={}},
                  ["Nurjak Vostra"]={DE="Nurjak Vostra", loc={}},
                  ["Avendrus Estate"]={DE="Avendrus-Anwesen", loc={}},
                  ["Life Factory"]={DE="Lebensfabrik", loc={}},
                  ["Gloamwood Pines"]={DE="Dämmerscheid", loc={}},
                  ["Kelrath Peninsula"]={DE="Kelrath-Halbinsel", loc={}},
                  ["Point Solitude"]={DE="Kap der Einsamkeit", loc={}},
                  ["Shatterbone Canyon"]={DE="Knochenberster-Canyon", loc={}},
                  ["Dream Hollow"]={DE="Traumhöhle", loc={}},
                  ["Granitewood Crossing"]={DE="Granitwaldkreuzung", loc={}},
                  ["Caer Thalos"]={DE="Caer Thalos", loc={}},
                  ["Fort Brevo"]={DE="Bastion Brevo", loc={}},
                  ["Shadefallen Towers"]={DE="Schattensturztürme", loc={}},
                  ["Tearfall Creek"]={DE="Zährenbach", loc={}},
                  ["Titan's Rest"]={DE="Titanenruh", loc={}},
                  ["Scarhide Waste"]={DE="Narbenhaut-Ödnis", loc={}},
                  ["Stoneborn Harbor"]={DE="Steingeborener Hafen", loc={}},
                  ["The Pus Swamp"]={DE="Das Eitermoor", loc={}}
}

---------- library public function block ---------

function EnKai.location.getSceneInfo(scene) return _scenes[scene] end